services:
  pipeless:
    image: registry.sdlc.lacak.io/pipeless-yolo-cpu:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - registry.sdlc.lacak.io/pipeless-yolo-cpu:0.0.1
    entrypoint: pipeless start --stages-dir .
    ports:
      - 3030:3030
    volumes:
      - ./:/app