services:
  pipeless:
    image: dev.local/pipeless:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - dev.local/pipeless:0.0.1
    entrypoint: pipeless start --stages-dir .
    ports:
      - 3030:3030
    volumes:
      - ./:/app